ALTER TABLE sales ADD COLUMN buyer_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN buyer_phone TEXT NOT NULL DEFAULT '',
    ADD COLUMN buyer_email TEXT NOT NULL DEFAULT '';

ALTER TABLE sales ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;
